#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows 10" {
        insmod search_fs_uuid
        insmod chain

	search --no-floppy --fs-uuid --set=root 32C8-19F7
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
